#!/bin/bash
project_name='Organizer'

function has-session {
  tmux has-session -t $project_name  2>/dev/null
}

if has-session ; then
  tmux a -t $project_name
else

  # main work directory:
  proj="$HOME/Documents/Nvim/Vimwiki/"
  tmux new-session -d -c $proj -s 'Organizer'
  # window 1: vimwiki
  tmux rename-window "Notes"
  tmux send-keys "nvim -c 'VimwikiIndex'" C-m
  # window 2: todo
  tmux new-window -c $proj
  tmux rename-window "Todo"
  tmux send-keys "nvim Main\ Todo.wiki" C-m
  # window 3: agenda
  tmux new-window -c $proj
  tmux rename-window "Agenda"
  tmux send-keys "nvim -c 'VimwikiDiaryIndex'" C-m
  tmux send-keys ":VimwikiDiaryGenerateLinks" C-m
  tmux send-keys ":w" C-m
  tmux send-keys "6ggw"
  tmux split-window -c -h -p 50
  tmux send-keys "nvim -c 'VimwikiMakeDiaryNote'" C-m
  tmux selectp -t 1
  # focus on window:
  tmux select-window -t "Todo"
  tmux attach-session -d
fi
