#!/bin/bash
project_name='FI-Mapping'

function has-session {
  tmux has-session -t=$project_name 2>/dev/null
}

if  has-session ; then
  tmux a -t $project_name
else

  # main work directory:
  bigproj="$HOME/Documents/Projects/FoodSecurity/5.Studies"
  proj="$bigproj/MapFoodInse"
  path_repos="$HOME/Documents/Repositories"
  tmux new-session -d -c $proj -s $project_name

  # window: notes
  tmux rename-window "Notes"
  tmux send-keys \
    'nvim ~/Documents/Nvim/Vimwiki/Food\ Insecurity\ Study\ Notes.wiki' C-m

  if [[ "$1" == *write* ]]; then
    # window: paper
    tmux new-window -c "$proj/7.Writing/paper-spmirt"
    tmux rename-window "Paper"
    tmux send-keys "nvim 00-paper.tex" C-m
    # window: outline
    tmux new-window -c "$proj/7.Writing/paper-spmirt"
    tmux rename-window "Outline"
    tmux send-keys "nvim README.md" C-m
  fi

  if [[ "$1" == *dev* ]]; then
    # window: package
    tmux new-window -c "$path_repos/spifa"
    tmux rename-window "Package"
    tmux send-keys "nvim" C-m
    # window: package test
    tmux new-window -c "$path_repos/spifa/demos"
    tmux rename-window "PackageDemos"
    tmux send-keys "nvim" C-m
  fi

  if [[ "$1" == *ana* ]]; then
    aux_path="$HOME/Documents/Repositories/Food-Security-Amazonia"
    aux_path+="/8.Analysis/5.FoodInsMapping/"
    # window: data analysis
    tmux new-window -c $aux_path
    tmux rename-window "Analysis"
    tmux send-keys "nvim" C-m
  fi

  # focus on window:
  tmux select-window -t "Notes"
  tmux attach-session -d
fi

