#!/bin/sh

project_name='Land-use'

has_session() {
    tmux has-session -t=$proj_name 2>/dev/null
}

if has-session; then
    tmux a -t $proj_name
else
    bigproj="$HOME/Documents/Projects/dsne"
    proj="$bigproj/land-use"
    tmux new-session -d -c $proj -s $project_name

    # window: notes
    tmux rename-window "Notes"
    tmux send-keys "nvim README.md" C-m

    # window: scripts 1
    tmux new-window -c "$proj/50-scripts"
    tmux rename-window "Scripts I"
    tmux send-keys 'nvim' C-m

    # window: scripts 2
    tmux new-window -c "$proj/50-scripts"
    tmux rename-window "Scripts II"
    tmux send-keys 'nvim' C-m

    # # window: makefile
    # tmux new-window -c "$proj"
    # tmux rename-window "Makefile"
    # tmux send-keys "nvim Makefile" C-m

    # focus on window:
    tmux select-window -t "Notes"
    tmux attach-session -d
fi
