#!/bin/sh

project_name='Statistics-II'

has_session() {
    tmux has-session -t $project_name 2>/dev/null
}

if has_session ; then
    tmux a -t $project_name -d
else
    bigproj="$HOME/Documents/Teaching/uni-undergraduate"
    proj="$bigproj/02-statistics-ii"
    tmux new-session -d -c $proj -s $project_name

    # window: notes
    tmux rename-window "Notes"
    tmux send-keys "nvim README.md" C-m

    # focus on window:
    tmux attach-session -d
fi

