#!/bin/sh

project_name='UK-data'

has_session() {
    tmux has-session -t $project_name 2>/dev/null
}

if has_session ; then
    tmux a -t $project_name -d
else
    bigproj="$HOME/Documents/Projects"
    proj="$bigproj/uk-data"
    tmux new-session -d -c $proj -s $project_name

    # window: notes
    tmux rename-window "Notes"
    tmux send-keys "nvim README.md" C-m

    # window: scripts 1
    tmux new-window -c "$proj/scripts"
    tmux rename-window "Scripts"
    tmux send-keys 'nvim' C-m

    # focus on window:
    tmux select-window -t "Notes"
    tmux attach-session -d
fi

