#!/bin/bash

project_name='Birth-weight'

function has-session {
    tmux has-session -t $project_name  2>/dev/null
}

if has-session ; then
    tmux attach-session -t $project_name -d
else
    bigproj="$HOME/Documents/Projects/data-amazonia"
    proj="$bigproj/70-studies/birthweight"
    tmux new-session -d -c $proj -s $project_name

    # window: notes
    tmux rename-window "Notes"
    tmux send-keys "nvim README.md" C-m

    # window: scripts
    tmux new-window -c "$proj/scripts"
    tmux rename-window "Scripts"
    tmux send-keys 'nvim' C-m

    # window: makefile
    tmux new-window -c "$proj"
    tmux rename-window "Makefile"
    tmux send-keys "nvim Makefile" C-m

    # focus on window:
    tmux select-window -t "Scripts"
    tmux attach-session -d
fi
