#!/bin/sh

project_name='Test'

has_session() {
    tmux has-session -t $project_name 2>/dev/null
}

if has_session ; then
    tmux attach-session -t $project_name -d
else
    tmux new-session -s $project_name
    tmux attach-session -d
fi
