#!/bin/bash
project_name='Repositories'

function has-session {
  tmux has-session -t=$project_name 2>/dev/null
}

if  has-session ; then
  tmux a -t $project_name
else

  # main work directory:
  proj="$HOME/Documents/Repositories"
  # path_repos="$HOME/Documents/Repositories"
  tmux new-session -d -c $proj -s $project_name

#   # window: notes
#   tmux rename-window "Main"
#   tmux send-keys 'nvim' C-m

  # if [[ "$1" == *docker* ]]; then
  #   aux_path="$HOME/Documents/Repositories/Food-Security-Amazonia"
  #   aux_path+="/8.Analysis/5.FoodInsMapping/"
  #   # window: data analysis
  #   tmux new-window -c $aux_path
  #   tmux rename-window "Analysis"
  #   tmux send-keys "nvim" C-m
  # fi

  # focus on window:
  tmux select-window -t "Main"
  tmux attach-session -d
fi

