#!/bin/sh

# ONLY AT STARTUP APPLICATIONS

killall -q sxhkd; sxhkd &                      # hotkeys
xsetroot -cursor_name left_ptr &               # mouse
/usr/lib/gnome-settings-daemon/gsd-xsettings & # gnome settings
gnome-flashback &                              # gnome utilities
gsettings set org.gnome.desktop.interface scaling-factor 2 # scale everything

$HOME/.local/bin/colors-01-random.sh           # random color
$HOME/.local/bin/colors-03-terminal.sh         # random color

$HOME/.config/bspwm/bspwmrc-monitors.sh             # monitors
bash $HOME/.config/polybar/launch.sh           # polybar
redshift &                                     # redshift for

$HOME/.config/bspwm/bspwmrc-custom.sh               # custom config
$HOME/.config/bspwm/bspwmrc-desktops.sh               # custom config


