#! /bin/sh

# Startup applications
feh --bg-fill "$HOME/.config/wall.png"
killall -q sxhkd && sxhkd &
bash $HOME/.local/bin/colors-terminal.sh
bash $HOME/.config/polybar/launch.sh

/usr/lib/gnome-settings-daemon/gsd-xsettings && \
gnome-flashback &

# gnome-flashback
# if ! pgrep -x gsd-xsettings > /dev/null
# then
# fi


# bspc monitor -d 1 2 3 4 5 6 7 8 9 10
bspc monitor eDP-1-1 -d 6 7 8 9
bspc monitor DP-1-1 -d 1 2 3 4 5
#bspc monitor VGA1 -d IV V VI

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.6
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# xrandr --dpi 220

# gnome integration

# gnome-power-manager
# /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

#redshift &

