#!/bin/bash
project_name='Thesis'

function has-session {
  tmux has-session -t=$project_name 2>/dev/null
}

if has-session ; then
  tmux a -t $project_name
else

  # main work directory:
  bigproj="$HOME/Documents/Projects/FoodSecurity/5.Studies/"
  proj="$bigproj/Thesis"
  tmux new-session -d -c $proj -s $project_name

  # window: notes
  tmux rename-window "Notes"
  tmux send-keys 'nvim README.md' C-m

  # window: paper
  tmux new-window -c $proj
  tmux rename-window "Intro"
  tmux send-keys "nvim" C-m

  # if [[ "$1" == *clean* ]]; then
  #   clean_path="$bigproj/3.CleanScripts"
  #   # window: cleaning
  #   tmux new-window -c $clean_path
  #   tmux rename-window "Cleaning"
  #   tmux send-keys "nvim" C-m
  # fi

  # if [[ "$1" == *ana* ]]; then
  #   aux_path="$HOME/Documents/Repositories/Food-Security-Amazonia"
  #   aux_path+="/8.Analysis/7.FoodInsMapping"
  #   # window: data analysis
  #   tmux new-window -c $aux_path
  #   tmux rename-window "Analysis"
  #   tmux send-keys "nvim" C-m
  # fi

  # if [[ "$1" == *dev* ]]; then
  #   # window: package
  #   tmux new-window -c "$HOME/Documents/Repositories/spifa"
  #   tmux rename-window "Package"
  #   tmux send-keys "nvim" C-m
  #   # window: package test
  #   tmux new-window -c "$HOME/Documents/Repositories/spifa/demos"
  #   tmux rename-window "PackageDemos"
  #   tmux send-keys "nvim" C-m
  # fi

  # if [[ "$1" == *repo* ]]; then
  #   # window: repositories
  #   tmux new-window -c "$HOME/Documents/Repositories"
  #   tmux rename-window "Repos"
  #   tmux send-keys "nvim" C-m
  # fi

  # if [[ "$1" == *paper* ]]; then
  #   # window: paper
  #   tmux new-window -c "$proj/7.Writing/paper-mapfi"
  #   tmux rename-window "Paper"
  #   tmux send-keys "nvim 00-paper.tex" C-m
  #   # window: outline
  #   tmux new-window -c "$proj/7.Writing/paper-mapfi"
  #   tmux rename-window "Outline"
  #   tmux send-keys "nvim README.md" C-m
  # fi

  # focus on window:
  tmux select-window -t "Notes"
  tmux attach-session -d
fi

