#!/bin/bash

function has-session {
  tmux has-session -t 'food'  2>/dev/null
}

if has-session ; then
  tmux a -t 'food'
  # echo "Session already exists"
else
  cd ~/Documents/Projects/FoodSecurity/3.CleanScripts
  tmux new-session -d -s 'food' 'nvim'
  tmux split-window -h -p 50
  tmux send-keys "nvim -c 'term R'" C-m
  tmux rename-window "R-Project"
  tmux new-window
  tmux rename-window "Notes"
  tmux send-keys "nvim -c 'VimwikiIndex'" C-m
  tmux split-window -h -p 50
  tmux send-keys "nvim -c 'e ~/Documents/Nvim/Vimwiki/Main\ Todo.md'" C-m
  # tmux split-window -h
  tmux selectp -t 1 # select the first (0) pane
  tmux select-window -t "R-Project"
  tmux selectp -t 1 # select the first (0) pane
  tmux attach-session -d
fi
